---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-crt
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: selfsigned
  commonName: keycloak.localtest.me
  dnsNames:
  - keycloak.localtest.me
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - keycloak.localtest.me
    secretName: tls-secret
  rules:
  - host: keycloak.localtest.me
    http:
      paths:
      - path: /
        backend:
          serviceName: app
          servicePort: http