# issuer.yaml
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: keycloak-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: me@localtest.me
    privateKeySecretRef:
      name: keycloak-issuer
    solvers:
    - http01:
        ingress:
          class: nginx
